### ISSUE TITLE
[FR] Custom @AUTOBIM GCode Command

### ISSUE THREAD

**Issue by jneilliii** [j-be/AutoBim#10]
It would be awesome if you could add a custom @AUTOBIM command to your plugin so that we could initialize the process from other please, ie OctoDash using Custom Actions. 

More information on implementation can be found here, works very similar to the gcode hooks you are already using. 

https://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-comm-protocol-atcommand-phase

**Comment by j-be** [comment]
Implemented, but still need to test it. Will release as soon as that is done.
