### ISSUE TITLE
3 Point leveling for Ender2

### ISSUE THREAD

**Issue by togeis** [j-be/AutoBim#14]
Autobim requires a 4 point leveling? My Ender2 has a 3 point leveling heatbed. Is it possible to make the number of points configurable?

**Comment by j-be** [comment]
Thanks for the suggestion. It is on my TODO list - didn't think it would come up that early. I will implement this as soon as I find a bit more time.

In the meantime I'd suggest setting 2 of the points to the same value. Not the nicest of workaround, but it should do the trick and not cause too much additional delay.

**Comment by j-be** [comment]
@togeis Sorry for the delay, I have been on holiday in the meantime, and things came up, and so on...

In any case: I implemented two buttons in settings allowing to add and remove corner points. This should allow for an arbitrary number of points. It is included in release 0.1.11.

Would you mind checking it and (assuming the feature works for you as well) close this issue? Thanks :smiley:

**Comment by j-be** [comment]
Closing the issue due to inactivity.
