### ISSUE TITLE
Stuck on "wait..."

### ISSUE THREAD

**Issue by rayge99** [j-be/AutoBim#35]
## Bug report

Please do not report the "Works fine on the first (or first and second corner), display says 'ok. moving to next' but
nothing happens" bug. This is covered in detail in the "Troubleshooting" section of the README. I know it is an issue
for many, and it is on the roadmap, but unfortunately it isn't an easy fix.

### Description
Briefly describe your issue.
After clicking to begin autobim just says wait... it does G28 then but never continues
I finally get the error
AutoBim aborted
Cannot probe X30 Y30! Please check settings!
I think It is because of the location it thinks is outside of the workable area?

### Steps to reproduce
click the autobim  button

What did you do to make the issue appear? More detailed is usually more better.
### Expected outcome
continue the autobim process

Describe what you expected would happen after you executed the steps above.
### Actual outcome
it sits there after a G28 is issue from autobim. 

Describe what actually happened.
### Environment (leave empty if unknown or not relevant)

* OctoPrint version: 
* Python version:
* Marlin version:
* Probe (e.g. BL-Touch, EZABL, ...):
* Printer (manufacturer/moodel, and please state any relevant modifications, like e.g. aftermarket mainboard):
* Browser (especially useful on UI issues):

For UI issues a screenshot always helps.

## Feature

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

Just describe what you would like AutoBim as detailed as you can.
## Question

Make sure your question is not covered by [the Troubleshooting section](https://github.com/j-be/AutoBim#troubleshooting).

Else: just fire away. But keep in mind: the more detail, the easier it is to answer :smiley:.

**Comment by sashgorokhov** [comment]
@rayge99 hey i was wondering how did you fixed the issue?

**Comment by j-be** [comment]
@sashgorokhov Did you make sure the points in settings are actually reachable by the probe? See "Test" button next to them in AutoBim's settings:

![image](https://user-images.githubusercontent.com/8503582/218069004-3c53e040-912d-4a31-b784-df8e055e4749.png)

Looks like I need to update the README on this.

If that is not the issue, maybe [this](https://github.com/j-be/AutoBim#printer-homes-moves-to-first-corner-probes-then-nothing-happens-display-is-stuck-on-wait) is?
