### ISSUE TITLE
UBL - G29 P0 is the wrong command

### ISSUE THREAD

**Issue by luketot** [j-be/AutoBim#5]
Haven't tried your plugin yet, but I will when I get the chance. This bug is based on a previous resolved issue.

For those of us using UBL, you issue G29 P0 to disable it before probing. Unfortunately, G29 P0 is not the right command. It doesn't disable UBL, it zeros the entire mesh. This is bad, as UBL meshes can take upwards of 15 minutes to generate. If someone were to save to EEPROM after running this, their mesh would be permanently erased, and they likely wouldn't know. Even without saving to EEPROM, their mesh would stay zeroed until they reboot the printer (or maybe just until re-loading the mesh).

The correct command is G29 D.

Although it makes sense to discard an existing non-UBL mesh (since the mesh will now be wrong), UBL has the tilt mesh feature (G29 J), so it will still accurately account for the warp of a bed.

**Comment by j-be** [comment]
@luketot thanks for the hint. Implemented and released a fixed verision.
