### ISSUE TITLE
Cannot get Z for corner

### ISSUE THREAD

**Issue by Dokturek991** [j-be/AutoBim#6]
Hello,

I am using P.I.N.D.A 2 clone probe on my Ender 3 PRO. It apprears that it might have a problem with probes that are normally open? I guess that BLTouch, for example, is normally closed. 

I am not an expert but it might be an issue. If not, just take it as a standard issue report with unknown cause.

Steps to reproduce:
1. Have a P.I.N.D.A 2 clone probe installed and configured with UBL
2. Open octoprint and start AutoBim
3. Printer homes while showing text "wait..."
4. Printer moves up a little, makes a multiple sounds (like when you use M500)
5. "3D Printer Ready" and nothing happens. Looks like it follows instructions to [STEP 2](https://github.com/j-be/AutoBim#what-is-supposed-to-happen) and then skips the others.

(I will send a video if needed.)

PS: I do have UBL set to true in your plugin. It is also updated to the latest version.
![AutoBim settings](https://user-images.githubusercontent.com/24963430/117821447-e2212580-b26b-11eb-9924-8b7363a32a36.png)

Hardware and firmware I'm using:
Ender 3 Pro
P.I.N.D.A 2 clone
Raspberry Pi Zero W
RepRapDiscount Full Graphic Smart Controller
SKR1.4 (LPC1768)
Marlin firmware 2.0.x bugfix (download: https://gofile.io/d/COue2N)

**Comment by MirekStanek** [comment]
```
Send: M117 wait...
Recv: ok
Send: G91
Recv: ok
Send: G28 X0 Y0 Z0
Recv: X:77.00 Y:121.00 Z:1.91 E:0.00 Count X:6160 Y:9680 Z:760
Recv: ok
Send: G90
Recv: ok
Send: G0 Z20
Recv: ok
Send: G29 D
Recv: Unified Bed Leveling System v1.01 inactive
Recv: ok
Send: G30 X30 Y30
Recv: ok
```
This is the state when it says just "3D Printer Ready"

So things that I have done here:
1. Restarted octoprint
2. Started AutoBim
3. Copied terminal output without temperature, SD, wait and processing responses

Wow, a few seconds ago it threw out additional output right after the previous one

```
Send: M117 Cannot get Z for corner ('30', '30')
Recv: ok
```

I did not notice this message before.
