### ISSUE TITLE
Add wait time before moving to other corner

### ISSUE THREAD

**Issue by MirekStanek** [j-be/AutoBim#7]
Suggestion:
Add a 2 second delay before moving to other corner.

Reason:
AutoBim tends to send move command to other corner immediately after desired distance is met while my big hand is still holding knob. It would be good if I had time to pull it out to avoid accidentally turning the knob with it.

Expected behaviour:
1. Measure Z distance until desired threshold is met
2. Move Z up a little to signal that conditions are met (or beep via M300)
3. Wait 1 - 2 seconds
4. Move to the other corner

**Comment by j-be** [comment]
Excellent idea. Got me a couple of times, too.

I'd say this should be a setting. Python takes floating point for `sleep`, so anybody would be free to tune it as he/she likes. Also, to not change behavior for existing users, I'd propose to let it default to zero.

So if a delay is set it would be like:

* `Hands off` on display - a later iteration may introduce a "small Z up - down" as additional choice, or even a "beep" (I hate those beeps :smile: )
* Wait `delay` seconds
* Move to next corner

Would that be ok?

**Comment by MirekStanek** [comment]
I don't think that `Hands off` on display is neccesary since you don't even need to look at the screen while using AutoBim. I'd rather use a little beep as a choice in the settings. 

Creating an item in the settings to adjust your own time before moving to the next corner is definitely a good idea. You should think about it and implement it in the next update. Thumbs up on this one, @j-be .
